language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjansson-dev asciidoc
before_script: ./autogen.sh
script:
  - make
  - make distcheck
